### ISSUE TITLE
Restore error: paramiko.ssh_exception.SSHException

### ISSUE THREAD

**Issue by adi-** [django-backup/django-backup#13]
```
File "/home/vagrant/.virtualenvs/gazex/src/django-backup-develop/django_backup/management/commands/restore.py", line 76, in handle
    is_folder = int(sftp.execute(cmd % media_remote_full_path)[0])
```

line above raises `paramiko.ssh_exception.SSHException: Channel closed.`

**Comment by andybak** [comment]
What's the value of:

```
cmd % media_remote_full_path
```

when it fails?

**Comment by adi-** [comment]
`u'if [[ -d "www-staging/dir_20150921-000001.tar.gz" ]]; then echo 1; else echo 0; fi'`

**Comment by andybak** [comment]
Can't recreate it. can you do a pip freeze and tell me the version numbers of pysftp, paramiko, ecdsa and pycrypto?

**Comment by adi-** [comment]
Maybe that could be a problem of specyfic sftp server? I am currently using [SolarWinds SFTP/SCP Server](http://www.solarwinds.com/products/freetools/free_tftp_server.aspx).

```
pysftp==0.2.8
paramiko==1.15.2
ecdsa==0.13
pycrypto==2.6.1
```

**Comment by andybak** [comment]
We're sending a fairly innocent command over ssh.

Can you sftp.execute anything on that connection? Maybe your account is set to deny some commands (i.e. it enforces the 'ftp' part of 'sftp' rather than allowing a full ssh connection)?

**Comment by adi-** [comment]
Ahhh, that could be the problem! I will investigate that, sir!

**Comment by adi-** [comment]
Done some research. You were right. I had shitty ssh/sftp server. So, I think it is time to close this ticket and mark it as `invalid`
