### ISSUE TITLE
Django 1.10 support

### ISSUE THREAD

**Issue by itatelier** [django-backup/django-backup#28]
I got this error while running on Django 1.10

`  File "c:\WWW\envs\doors\lib\site-packages\django-backup\management\commands\backup.py", line 14, in Command
    option_list = BaseCommand.option_list + (
AttributeError: type object 'BaseCommand' has no attribute 'option_list'`

BaseCommand.option_list Deprecated since version 1.8

**Comment by fruitschen** [comment]
added support for django1.10
