### ISSUE TITLE
SFTP Support Refactoring

### ISSUE THREAD

**Issue by zerok** [django-backup/django-backup#3]
Right now we require a forked version of the pysftp package. From what I can see the initial reason for that was that the upstream package didn't have a mkdir method. This seems to have changed over the years.

A problem with moving to the official pysftp package is, though, that we can't easily create tests to make sure we don't break anything. pytest has a sftpserver plugin but other than that I haven't found anything comparable.

**Comment by zerok** [comment]
@andybak: I've managed to get basic testing for SFTP uploads running now with the help of pytest and pytest-sftpserver. I'll start refactoring the testsuite to use that one instead of Django's built-in test-system if you don't mind. This should also make our 2 existing tests better readable and facilitate future testing :-)

**Comment by andybak** [comment]
That sounds fine. Sorry I can't be more help. I'm currently tied up with other stuff.

**Comment by zerok** [comment]
No worries ☺
On 17 May 2015 2:57 pm, Andy Baker notifications@github.com wrote:That sounds fine. Sorry I can't be more help. I'm currently tied up with other stuff.

**Comment by zerok** [comment]
A small status update: I've integrated pytest-sftpserver to make sure that the basics of the upload functionality still work and discovered some issues with it under Python 3.x. Other than that the upstream pysftp package seems to work fine as a drop-in-replacement. Now I'm waiting for some fixes in pytest-sftpserver before I can continue testing there :)

**Comment by zerok** [comment]
458480955e9896bb5886c3ff2d6a3c9e6e203723 removes the dependency on the custom fork.
